apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-zrly
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-zrly
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-zrly
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-zrly
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-zrly
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uhnt-tenant/rhtap-demo-app/hacbs-test-project-zrly@sha256:7fd0fbddf69662fc27e25d55839b3ac17ab7bde8b35ebae56b05526609cccf91
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
